/* The following code was generated by JFlex 1.4.3 on 27/11/17 11:11 AM */

package mx.edu.ittepic.automatas;

import static mx.edu.ittepic.automatas.Token.*;
import mx.edu.ittepic.automatas.Token;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/11/17 11:11 AM from the specification file
 * <tt>/Users/Mannlex21/Documents/GitHub/AbbyScript/src/mx/edu/ittepic/automatas/Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\4\1\0\1\0\1\4\22\0\1\4\1\6\1\3"+
    "\3\0\1\26\1\0\1\13\1\15\1\10\1\31\1\24\1\7\1\14"+
    "\1\32\12\2\1\25\1\23\1\5\1\30\1\11\2\0\1\42\1\57"+
    "\1\33\1\52\1\53\1\46\1\56\1\35\1\44\1\54\1\60\1\40"+
    "\1\37\1\45\1\50\1\55\1\104\1\43\1\34\1\36\1\47\1\41"+
    "\1\62\1\61\1\51\1\1\1\20\1\112\1\21\1\27\1\22\1\0"+
    "\1\71\1\102\1\70\1\74\1\66\1\103\1\73\1\77\1\100\1\1"+
    "\1\111\1\67\1\76\1\106\1\63\1\64\1\1\1\75\1\72\1\65"+
    "\1\110\1\107\1\1\1\101\1\105\1\1\1\16\1\12\1\17\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\5\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\33\2\1\3\1\33\1\0"+
    "\1\34\1\0\1\35\1\36\1\37\1\40\1\41\1\0"+
    "\1\42\1\43\1\0\1\44\1\45\1\46\1\47\1\50"+
    "\6\2\1\51\2\2\1\52\11\2\1\53\1\54\7\2"+
    "\1\55\5\2\1\56\14\2\1\33\3\0\1\57\1\60"+
    "\10\2\1\61\3\2\1\62\1\63\11\2\1\64\13\2"+
    "\1\65\3\2\1\66\1\2\1\67\3\2\4\0\1\3"+
    "\4\2\1\70\1\71\1\2\1\72\1\73\1\74\1\75"+
    "\7\2\1\76\3\2\1\77\1\2\1\100\2\2\1\101"+
    "\24\2\2\0\1\102\1\0\1\33\1\103\2\2\1\104"+
    "\1\105\1\106\1\2\1\107\4\2\1\110\6\2\1\111"+
    "\1\112\15\2\1\113\5\2\2\0\1\114\1\115\1\2"+
    "\1\116\1\117\1\120\1\121\1\122\4\2\1\123\11\2"+
    "\1\124\6\2\1\125\2\2\1\0\1\126\3\2\1\127"+
    "\3\2\1\130\1\131\1\2\1\132\3\2\1\133\1\134"+
    "\1\135\5\2\1\126\1\2\1\136\2\2\1\137\3\2"+
    "\1\140\5\2\1\141\1\142\1\143\1\2\1\144\1\145"+
    "\1\2\1\146\2\2\1\147\1\2\1\150\1\151\7\2"+
    "\1\152\3\2\1\153\1\154\1\2\1\155\3\2\1\156"+
    "\1\157";

  private static int [] zzUnpackAction() {
    int [] result = new int[377];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\113\0\226\0\341\0\u012c\0\113\0\u0177\0\u01c2"+
    "\0\u020d\0\u0258\0\u02a3\0\u02ee\0\u0339\0\113\0\113\0\113"+
    "\0\113\0\113\0\113\0\226\0\113\0\113\0\113\0\u0384"+
    "\0\113\0\u03cf\0\u041a\0\u0465\0\u04b0\0\u04fb\0\u0546\0\u0591"+
    "\0\u05dc\0\u0627\0\u0672\0\u06bd\0\u0708\0\u0753\0\u079e\0\u07e9"+
    "\0\u0834\0\u087f\0\u08ca\0\u0915\0\u0960\0\u09ab\0\u09f6\0\u0a41"+
    "\0\u0a8c\0\u0ad7\0\u0b22\0\u0b6d\0\u0bb8\0\u0c03\0\u0c4e\0\u0c99"+
    "\0\u0c99\0\u012c\0\113\0\u0ce4\0\113\0\113\0\113\0\113"+
    "\0\113\0\u0d2f\0\113\0\113\0\u0d7a\0\113\0\u0dc5\0\113"+
    "\0\113\0\113\0\u0e10\0\u0e5b\0\u0ea6\0\u0ef1\0\u0f3c\0\u0f87"+
    "\0\226\0\u0fd2\0\u101d\0\u1068\0\u10b3\0\u10fe\0\u1149\0\u1194"+
    "\0\u11df\0\u122a\0\u1275\0\u12c0\0\u130b\0\226\0\226\0\u1356"+
    "\0\u13a1\0\u13ec\0\u1437\0\u1482\0\u14cd\0\u1518\0\226\0\u1563"+
    "\0\u15ae\0\u15f9\0\u1644\0\u168f\0\226\0\u16da\0\u1725\0\u1770"+
    "\0\u17bb\0\u1806\0\u1851\0\u189c\0\u18e7\0\u1932\0\u197d\0\u19c8"+
    "\0\u1a13\0\u1a5e\0\u1aa9\0\u1af4\0\u1b3f\0\113\0\226\0\u1b8a"+
    "\0\u1bd5\0\u1c20\0\u1c6b\0\u1cb6\0\u1d01\0\u1d4c\0\u1d97\0\226"+
    "\0\u1de2\0\u1e2d\0\u1e78\0\226\0\u1ec3\0\u1f0e\0\u1f59\0\u1fa4"+
    "\0\u1fef\0\u203a\0\u2085\0\u20d0\0\u211b\0\u2166\0\u21b1\0\u21fc"+
    "\0\u2247\0\u2292\0\u22dd\0\u2328\0\u2373\0\u23be\0\u2409\0\u2454"+
    "\0\u249f\0\u24ea\0\226\0\u2535\0\u2580\0\u25cb\0\226\0\u2616"+
    "\0\226\0\u2661\0\u26ac\0\u26f7\0\u1a5e\0\u2742\0\u278d\0\u27d8"+
    "\0\113\0\u2823\0\u286e\0\u28b9\0\u2904\0\226\0\226\0\u294f"+
    "\0\226\0\226\0\226\0\226\0\u299a\0\u29e5\0\u2a30\0\u2a7b"+
    "\0\u2ac6\0\u2b11\0\u2b5c\0\226\0\u2ba7\0\u2bf2\0\u2c3d\0\226"+
    "\0\u2c88\0\226\0\u2cd3\0\u2d1e\0\226\0\u2d69\0\u2db4\0\u2dff"+
    "\0\u2e4a\0\u2e95\0\u2ee0\0\u2f2b\0\u2f76\0\u2fc1\0\u300c\0\u3057"+
    "\0\u30a2\0\u30ed\0\u3138\0\u3183\0\u31ce\0\u3219\0\u3264\0\u32af"+
    "\0\u32fa\0\u3345\0\u3390\0\113\0\u33db\0\113\0\226\0\u3426"+
    "\0\u3471\0\u34bc\0\226\0\226\0\u3507\0\226\0\u3552\0\u359d"+
    "\0\u35e8\0\u3633\0\226\0\u367e\0\u36c9\0\u3714\0\u375f\0\u37aa"+
    "\0\u37f5\0\226\0\226\0\u3840\0\u388b\0\u38d6\0\u3921\0\u396c"+
    "\0\u39b7\0\u3a02\0\u3a4d\0\u3a98\0\u3ae3\0\u3b2e\0\u3b79\0\u3bc4"+
    "\0\226\0\u3c0f\0\u3c5a\0\u3ca5\0\u3cf0\0\u3d3b\0\u3d86\0\u3dd1"+
    "\0\226\0\226\0\u3e1c\0\226\0\226\0\226\0\226\0\226"+
    "\0\u3e67\0\u3eb2\0\u3efd\0\u3f48\0\226\0\u3f93\0\u3fde\0\u4029"+
    "\0\u4074\0\u40bf\0\u410a\0\u4155\0\u41a0\0\u41eb\0\226\0\u4236"+
    "\0\u4281\0\u42cc\0\u4317\0\u4362\0\u43ad\0\226\0\u43f8\0\u4443"+
    "\0\u448e\0\u3345\0\u44d9\0\u4524\0\u456f\0\226\0\u45ba\0\u4605"+
    "\0\u4650\0\226\0\226\0\u469b\0\226\0\u46e6\0\u4731\0\u477c"+
    "\0\226\0\226\0\226\0\u47c7\0\u4812\0\u485d\0\u48a8\0\u48f3"+
    "\0\113\0\u493e\0\226\0\u4989\0\u49d4\0\226\0\u4a1f\0\u4a6a"+
    "\0\u4ab5\0\226\0\u4b00\0\u4b4b\0\u4b96\0\u4be1\0\u4c2c\0\226"+
    "\0\226\0\226\0\u4c77\0\226\0\226\0\u4cc2\0\226\0\u4d0d"+
    "\0\u4d58\0\226\0\u4da3\0\226\0\226\0\u4dee\0\u4e39\0\u4e84"+
    "\0\u4ecf\0\u4f1a\0\u4f65\0\u4fb0\0\226\0\u4ffb\0\u5046\0\u5091"+
    "\0\226\0\u50dc\0\u5127\0\226\0\u5172\0\u51bd\0\u5208\0\226"+
    "\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[377];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\3\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\3\3"+
    "\1\50\1\51\1\52\1\53\1\3\1\54\2\3\1\55"+
    "\1\56\4\3\1\57\1\3\1\60\1\61\1\62\1\3"+
    "\1\63\1\64\1\65\1\3\1\66\1\67\6\3\1\2"+
    "\114\0\2\3\17\0\1\3\10\0\57\3\3\0\1\70"+
    "\11\0\1\71\76\0\3\72\1\73\106\72\7\0\1\74"+
    "\21\0\1\75\112\0\1\76\71\0\1\77\20\0\1\100"+
    "\112\0\1\101\71\0\1\102\20\0\1\103\74\0\1\104"+
    "\107\0\1\105\131\0\1\106\114\0\1\107\112\0\1\110"+
    "\1\111\111\0\1\112\63\0\2\3\17\0\1\3\10\0"+
    "\1\3\1\113\5\3\1\114\1\115\4\3\1\116\26\3"+
    "\1\117\12\3\2\0\2\3\17\0\1\3\10\0\3\3"+
    "\1\120\17\3\1\121\33\3\2\0\2\3\17\0\1\3"+
    "\10\0\2\3\1\122\4\3\1\123\1\124\46\3\2\0"+
    "\2\3\17\0\1\3\10\0\7\3\1\125\47\3\2\0"+
    "\2\3\17\0\1\3\10\0\11\3\1\126\45\3\2\0"+
    "\2\3\17\0\1\3\10\0\7\3\1\127\26\3\1\130"+
    "\20\3\2\0\2\3\17\0\1\3\10\0\1\131\7\3"+
    "\1\132\46\3\2\0\2\3\17\0\1\3\10\0\1\133"+
    "\17\3\1\134\12\3\1\135\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\12\3\1\136\1\137\43\3\2\0\2\3"+
    "\17\0\1\3\10\0\14\3\1\140\42\3\2\0\2\3"+
    "\17\0\1\3\10\0\7\3\1\141\4\3\1\142\1\143"+
    "\41\3\2\0\2\3\17\0\1\3\10\0\7\3\1\144"+
    "\10\3\1\145\36\3\2\0\2\3\17\0\1\3\10\0"+
    "\5\3\1\146\51\3\2\0\2\3\17\0\1\3\10\0"+
    "\1\3\1\147\47\3\1\150\5\3\2\0\2\3\17\0"+
    "\1\3\10\0\7\3\1\151\32\3\1\152\14\3\2\0"+
    "\2\3\17\0\1\3\10\0\10\3\1\153\46\3\2\0"+
    "\2\3\17\0\1\3\10\0\2\3\1\154\14\3\1\155"+
    "\37\3\2\0\2\3\17\0\1\3\10\0\31\3\1\156"+
    "\23\3\1\157\1\3\2\0\2\3\17\0\1\3\10\0"+
    "\37\3\1\160\17\3\2\0\2\3\17\0\1\3\10\0"+
    "\33\3\1\161\23\3\2\0\2\3\17\0\1\3\10\0"+
    "\33\3\1\162\23\3\2\0\2\3\17\0\1\3\10\0"+
    "\30\3\1\163\14\3\1\164\11\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\165\20\3\2\0\2\3\17\0"+
    "\1\3\10\0\54\3\1\166\2\3\2\0\2\3\17\0"+
    "\1\3\10\0\53\3\1\167\3\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\170\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\45\3\1\171\11\3\3\0\1\70\11\0"+
    "\1\172\105\0\1\173\103\0\10\174\1\0\102\174\2\0"+
    "\1\175\140\0\1\176\63\0\2\3\17\0\1\3\10\0"+
    "\1\3\1\177\55\3\2\0\2\3\17\0\1\3\10\0"+
    "\3\3\1\200\53\3\2\0\2\3\17\0\1\3\10\0"+
    "\20\3\1\201\36\3\2\0\2\3\17\0\1\3\10\0"+
    "\12\3\1\202\44\3\2\0\2\3\17\0\1\3\10\0"+
    "\45\3\1\203\11\3\2\0\2\3\17\0\1\3\10\0"+
    "\4\3\1\204\52\3\2\0\2\3\17\0\1\3\10\0"+
    "\11\3\1\205\45\3\2\0\2\3\17\0\1\3\10\0"+
    "\24\3\1\206\32\3\2\0\2\3\17\0\1\3\10\0"+
    "\14\3\1\207\1\3\1\210\40\3\2\0\2\3\17\0"+
    "\1\3\10\0\11\3\1\211\10\3\1\212\34\3\2\0"+
    "\2\3\17\0\1\3\10\0\1\3\1\213\55\3\2\0"+
    "\2\3\17\0\1\3\10\0\10\3\1\214\46\3\2\0"+
    "\2\3\17\0\1\3\10\0\34\3\1\215\22\3\2\0"+
    "\2\3\17\0\1\3\10\0\34\3\1\216\22\3\2\0"+
    "\2\3\17\0\1\3\10\0\10\3\1\217\46\3\2\0"+
    "\2\3\17\0\1\3\10\0\34\3\1\220\7\3\1\221"+
    "\12\3\2\0\2\3\17\0\1\3\10\0\3\3\1\222"+
    "\53\3\2\0\2\3\17\0\1\3\10\0\43\3\1\223"+
    "\13\3\2\0\2\3\17\0\1\3\10\0\5\3\1\224"+
    "\51\3\2\0\2\3\17\0\1\3\10\0\5\3\1\225"+
    "\51\3\2\0\2\3\17\0\1\3\10\0\12\3\1\226"+
    "\44\3\2\0\2\3\17\0\1\3\10\0\10\3\1\227"+
    "\46\3\2\0\2\3\17\0\1\3\10\0\3\3\1\230"+
    "\53\3\2\0\2\3\17\0\1\3\10\0\1\231\56\3"+
    "\2\0\2\3\17\0\1\3\10\0\1\3\1\232\55\3"+
    "\2\0\2\3\17\0\1\3\10\0\17\3\1\233\1\234"+
    "\36\3\2\0\2\3\17\0\1\3\10\0\23\3\1\235"+
    "\33\3\2\0\2\3\17\0\1\3\10\0\45\3\1\236"+
    "\11\3\2\0\2\3\17\0\1\3\10\0\20\3\1\237"+
    "\36\3\2\0\2\3\17\0\1\3\10\0\11\3\1\240"+
    "\45\3\2\0\2\3\17\0\1\3\10\0\32\3\1\241"+
    "\24\3\2\0\2\3\17\0\1\3\10\0\32\3\1\242"+
    "\24\3\2\0\2\3\17\0\1\3\10\0\37\3\1\243"+
    "\17\3\2\0\2\3\17\0\1\3\10\0\32\3\1\244"+
    "\24\3\2\0\2\3\17\0\1\3\10\0\32\3\1\245"+
    "\24\3\2\0\2\3\17\0\1\3\10\0\35\3\1\246"+
    "\21\3\2\0\2\3\17\0\1\3\10\0\54\3\1\247"+
    "\2\3\2\0\2\3\17\0\1\3\10\0\56\3\1\250"+
    "\2\0\2\3\17\0\1\3\10\0\42\3\1\251\14\3"+
    "\2\0\2\3\17\0\1\3\10\0\2\3\1\252\54\3"+
    "\2\0\2\3\17\0\1\3\10\0\50\3\1\253\6\3"+
    "\2\0\2\3\17\0\1\3\10\0\34\3\1\254\22\3"+
    "\3\0\1\255\11\0\1\172\105\0\1\256\103\0\6\174"+
    "\1\257\104\174\2\0\1\175\11\0\1\260\1\261\76\0"+
    "\2\3\17\0\1\3\10\0\1\262\56\3\2\0\2\3"+
    "\17\0\1\3\10\0\7\3\1\263\47\3\2\0\2\3"+
    "\17\0\1\3\10\0\1\3\1\264\55\3\2\0\2\3"+
    "\17\0\1\3\10\0\34\3\1\265\22\3\2\0\2\3"+
    "\17\0\1\3\10\0\5\3\1\266\51\3\2\0\2\3"+
    "\17\0\1\3\10\0\1\3\1\267\55\3\2\0\2\3"+
    "\17\0\1\3\10\0\5\3\1\270\51\3\2\0\2\3"+
    "\17\0\1\3\10\0\20\3\1\271\36\3\2\0\2\3"+
    "\17\0\1\3\10\0\12\3\1\272\44\3\2\0\2\3"+
    "\17\0\1\3\10\0\26\3\1\273\30\3\2\0\2\3"+
    "\17\0\1\3\10\0\3\3\1\274\53\3\2\0\2\3"+
    "\17\0\1\3\10\0\55\3\1\275\1\3\2\0\2\3"+
    "\17\0\1\3\10\0\36\3\1\276\20\3\2\0\2\3"+
    "\17\0\1\3\10\0\7\3\1\277\47\3\2\0\2\3"+
    "\17\0\1\3\10\0\36\3\1\300\20\3\2\0\2\3"+
    "\17\0\1\3\10\0\45\3\1\301\11\3\2\0\2\3"+
    "\17\0\1\3\10\0\14\3\1\302\42\3\2\0\2\3"+
    "\17\0\1\3\10\0\30\3\1\303\26\3\2\0\2\3"+
    "\17\0\1\3\10\0\5\3\1\304\51\3\2\0\2\3"+
    "\17\0\1\3\10\0\1\3\1\305\55\3\2\0\2\3"+
    "\17\0\1\3\10\0\1\306\56\3\2\0\2\3\17\0"+
    "\1\3\10\0\4\3\1\307\52\3\2\0\2\3\17\0"+
    "\1\3\10\0\20\3\1\310\36\3\2\0\2\3\17\0"+
    "\1\3\10\0\5\3\1\311\51\3\2\0\2\3\17\0"+
    "\1\3\10\0\20\3\1\312\36\3\2\0\2\3\17\0"+
    "\1\3\10\0\30\3\1\313\26\3\2\0\2\3\17\0"+
    "\1\3\10\0\34\3\1\314\22\3\2\0\2\3\17\0"+
    "\1\3\10\0\20\3\1\315\36\3\2\0\2\3\17\0"+
    "\1\3\10\0\53\3\1\316\3\3\2\0\2\3\17\0"+
    "\1\3\10\0\7\3\1\317\47\3\2\0\2\3\17\0"+
    "\1\3\10\0\5\3\1\320\51\3\2\0\2\3\17\0"+
    "\1\3\10\0\1\3\1\321\55\3\2\0\2\3\17\0"+
    "\1\3\10\0\2\3\1\322\54\3\2\0\2\3\17\0"+
    "\1\3\10\0\2\3\1\323\54\3\2\0\2\3\17\0"+
    "\1\3\10\0\1\3\1\324\1\325\1\3\1\326\2\3"+
    "\1\327\6\3\1\330\1\331\4\3\1\332\32\3\2\0"+
    "\2\3\17\0\1\3\10\0\1\333\14\3\1\334\5\3"+
    "\1\335\33\3\2\0\2\3\17\0\1\3\10\0\33\3"+
    "\1\336\23\3\2\0\2\3\17\0\1\3\10\0\3\3"+
    "\1\337\53\3\2\0\2\3\17\0\1\3\10\0\30\3"+
    "\1\340\26\3\2\0\2\3\17\0\1\3\10\0\33\3"+
    "\1\341\23\3\1\0\7\342\1\343\1\0\102\342\5\174"+
    "\1\344\1\257\104\174\2\0\1\345\11\0\1\260\1\346"+
    "\76\0\2\3\17\0\1\3\10\0\2\3\1\347\54\3"+
    "\2\0\2\3\17\0\1\3\10\0\3\3\1\350\53\3"+
    "\2\0\2\3\17\0\1\3\10\0\15\3\1\351\41\3"+
    "\2\0\2\3\17\0\1\3\10\0\41\3\1\352\15\3"+
    "\2\0\2\3\17\0\1\3\10\0\20\3\1\353\36\3"+
    "\2\0\2\3\17\0\1\3\10\0\33\3\1\354\23\3"+
    "\2\0\2\3\17\0\1\3\10\0\37\3\1\355\17\3"+
    "\2\0\2\3\17\0\1\3\10\0\16\3\1\356\40\3"+
    "\2\0\2\3\17\0\1\3\10\0\37\3\1\357\17\3"+
    "\2\0\2\3\17\0\1\3\10\0\34\3\1\360\22\3"+
    "\2\0\2\3\17\0\1\3\10\0\10\3\1\361\46\3"+
    "\2\0\2\3\17\0\1\3\10\0\54\3\1\362\2\3"+
    "\2\0\2\3\17\0\1\3\10\0\20\3\1\363\36\3"+
    "\2\0\2\3\17\0\1\3\10\0\3\3\1\364\53\3"+
    "\2\0\2\3\17\0\1\3\10\0\7\3\1\365\47\3"+
    "\2\0\2\3\17\0\1\3\10\0\7\3\1\366\47\3"+
    "\2\0\2\3\17\0\1\3\10\0\35\3\1\367\21\3"+
    "\2\0\2\3\17\0\1\3\10\0\33\3\1\370\23\3"+
    "\2\0\2\3\17\0\1\3\10\0\32\3\1\371\24\3"+
    "\2\0\2\3\17\0\1\3\10\0\25\3\1\372\31\3"+
    "\2\0\2\3\17\0\1\3\10\0\20\3\1\373\36\3"+
    "\2\0\2\3\17\0\1\3\10\0\33\3\1\374\23\3"+
    "\2\0\2\3\17\0\1\3\10\0\3\3\1\375\53\3"+
    "\2\0\2\3\17\0\1\3\10\0\3\3\1\376\53\3"+
    "\2\0\2\3\17\0\1\3\10\0\33\3\1\377\23\3"+
    "\2\0\2\3\17\0\1\3\10\0\30\3\1\u0100\26\3"+
    "\2\0\2\3\17\0\1\3\10\0\1\3\1\u0101\26\3"+
    "\1\u0102\14\3\1\u0103\11\3\2\0\2\3\17\0\1\3"+
    "\10\0\32\3\1\u0104\24\3\2\0\2\3\17\0\1\3"+
    "\10\0\33\3\1\u0105\23\3\2\0\2\3\17\0\1\3"+
    "\10\0\36\3\1\u0106\20\3\2\0\2\3\17\0\1\3"+
    "\10\0\30\3\1\u0107\26\3\2\0\2\3\17\0\1\3"+
    "\10\0\42\3\1\u0108\14\3\2\0\2\3\17\0\1\3"+
    "\10\0\53\3\1\u0109\3\3\2\0\2\3\17\0\1\3"+
    "\10\0\33\3\1\u010a\23\3\2\0\2\3\17\0\1\3"+
    "\10\0\3\3\1\u010b\53\3\2\0\2\3\17\0\1\3"+
    "\10\0\4\3\1\u010c\52\3\2\0\2\3\17\0\1\3"+
    "\10\0\42\3\1\u010d\14\3\2\0\2\3\17\0\1\3"+
    "\10\0\12\3\1\u010e\44\3\1\0\7\342\1\u010f\112\342"+
    "\1\u0110\103\342\2\0\1\345\11\0\1\260\77\0\2\3"+
    "\17\0\1\3\10\0\20\3\1\u0111\36\3\2\0\2\3"+
    "\17\0\1\3\10\0\5\3\1\u0112\51\3\2\0\2\3"+
    "\17\0\1\3\10\0\3\3\1\u0113\53\3\2\0\2\3"+
    "\17\0\1\3\10\0\37\3\1\u0114\17\3\2\0\2\3"+
    "\17\0\1\3\10\0\37\3\1\u0115\17\3\2\0\2\3"+
    "\17\0\1\3\10\0\41\3\1\u0116\15\3\2\0\2\3"+
    "\17\0\1\3\10\0\12\3\1\u0117\44\3\2\0\2\3"+
    "\17\0\1\3\10\0\33\3\1\u0118\23\3\2\0\2\3"+
    "\17\0\1\3\10\0\11\3\1\u0119\45\3\2\0\2\3"+
    "\17\0\1\3\10\0\3\3\1\u011a\53\3\2\0\2\3"+
    "\17\0\1\3\10\0\10\3\1\u011b\46\3\2\0\2\3"+
    "\17\0\1\3\10\0\10\3\1\u011c\46\3\2\0\2\3"+
    "\17\0\1\3\10\0\43\3\1\u011d\13\3\2\0\2\3"+
    "\17\0\1\3\10\0\1\u011e\56\3\2\0\2\3\17\0"+
    "\1\3\10\0\34\3\1\u011f\22\3\2\0\2\3\17\0"+
    "\1\3\10\0\4\3\1\u0120\52\3\2\0\2\3\17\0"+
    "\1\3\10\0\4\3\1\u0121\52\3\2\0\2\3\17\0"+
    "\1\3\10\0\35\3\1\u0122\21\3\2\0\2\3\17\0"+
    "\1\3\10\0\55\3\1\u0123\1\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u0124\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\53\3\1\u0125\3\3\2\0\2\3\17\0"+
    "\1\3\10\0\53\3\1\u0126\3\3\2\0\2\3\17\0"+
    "\1\3\10\0\32\3\1\u0127\24\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\u0128\20\3\2\0\2\3\17\0"+
    "\1\3\10\0\32\3\1\u0129\24\3\2\0\2\3\17\0"+
    "\1\3\10\0\41\3\1\u012a\15\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u012b\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\32\3\1\u012c\24\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\u012d\20\3\2\0\2\3\17\0"+
    "\1\3\10\0\5\3\1\u012e\51\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u012f\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\u0130\20\3\1\0\7\342\1\u0131"+
    "\112\342\1\u0131\1\342\1\u0132\101\342\1\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u0133\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\15\3\1\u0134\41\3\2\0\2\3\17\0"+
    "\1\3\10\0\3\3\1\u0135\53\3\2\0\2\3\17\0"+
    "\1\3\10\0\20\3\1\u0136\36\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u0137\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\30\3\1\u0138\26\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u0139\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\5\3\1\u013a\51\3\2\0\2\3\17\0"+
    "\1\3\10\0\5\3\1\u013b\51\3\2\0\2\3\17\0"+
    "\1\3\10\0\30\3\1\u013c\26\3\2\0\2\3\17\0"+
    "\1\3\10\0\42\3\1\u013d\14\3\2\0\2\3\17\0"+
    "\1\3\10\0\35\3\1\u013e\21\3\2\0\2\3\17\0"+
    "\1\3\10\0\32\3\1\u013f\24\3\2\0\2\3\17\0"+
    "\1\3\10\0\55\3\1\u0140\1\3\2\0\2\3\17\0"+
    "\1\3\10\0\42\3\1\u0141\14\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u0142\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\52\3\1\u0143\4\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\u0144\20\3\2\0\2\3\17\0"+
    "\1\3\10\0\20\3\1\u0145\36\3\2\0\2\3\17\0"+
    "\1\3\10\0\47\3\1\u0146\7\3\2\0\2\3\17\0"+
    "\1\3\10\0\1\u0147\56\3\2\0\2\3\17\0\1\3"+
    "\10\0\43\3\1\u0148\13\3\1\0\7\342\1\u0131\1\342"+
    "\1\u0149\101\342\1\0\2\3\17\0\1\3\10\0\46\3"+
    "\1\u014a\10\3\2\0\2\3\17\0\1\3\10\0\12\3"+
    "\1\u014b\44\3\2\0\2\3\17\0\1\3\10\0\20\3"+
    "\1\u014c\36\3\2\0\2\3\17\0\1\3\10\0\36\3"+
    "\1\u014d\20\3\2\0\2\3\17\0\1\3\10\0\53\3"+
    "\1\u014e\3\3\2\0\2\3\17\0\1\3\10\0\35\3"+
    "\1\u014f\21\3\2\0\2\3\17\0\1\3\10\0\53\3"+
    "\1\u0150\3\3\2\0\2\3\17\0\1\3\10\0\30\3"+
    "\1\u0151\26\3\2\0\2\3\17\0\1\3\10\0\44\3"+
    "\1\u0152\12\3\2\0\2\3\17\0\1\3\10\0\32\3"+
    "\1\u0153\24\3\2\0\2\3\17\0\1\3\10\0\32\3"+
    "\1\u0154\24\3\2\0\2\3\17\0\1\3\10\0\34\3"+
    "\1\u0155\22\3\2\0\2\3\17\0\1\3\10\0\34\3"+
    "\1\u0156\22\3\2\0\2\3\17\0\1\3\10\0\44\3"+
    "\1\u0157\12\3\2\0\2\3\17\0\1\3\10\0\33\3"+
    "\1\u0158\23\3\2\0\2\3\17\0\1\3\10\0\32\3"+
    "\1\u0159\24\3\2\0\2\3\17\0\1\3\10\0\10\3"+
    "\1\u015a\46\3\2\0\2\3\17\0\1\3\10\0\41\3"+
    "\1\u015b\15\3\2\0\2\3\17\0\1\3\10\0\32\3"+
    "\1\u015c\24\3\2\0\2\3\17\0\1\3\10\0\41\3"+
    "\1\u015d\15\3\2\0\2\3\17\0\1\3\10\0\53\3"+
    "\1\u015e\3\3\2\0\2\3\17\0\1\3\10\0\33\3"+
    "\1\u015f\23\3\2\0\2\3\17\0\1\3\10\0\33\3"+
    "\1\u0160\23\3\2\0\2\3\17\0\1\3\10\0\33\3"+
    "\1\u0161\23\3\2\0\2\3\17\0\1\3\10\0\33\3"+
    "\1\u0162\23\3\2\0\2\3\17\0\1\3\10\0\45\3"+
    "\1\u0163\11\3\2\0\2\3\17\0\1\3\10\0\52\3"+
    "\1\u0164\4\3\2\0\2\3\17\0\1\3\10\0\41\3"+
    "\1\u0165\15\3\2\0\2\3\17\0\1\3\10\0\20\3"+
    "\1\u0166\36\3\2\0\2\3\17\0\1\3\10\0\43\3"+
    "\1\u0167\13\3\2\0\2\3\17\0\1\3\10\0\34\3"+
    "\1\u0168\22\3\2\0\2\3\17\0\1\3\10\0\34\3"+
    "\1\u0169\22\3\2\0\2\3\17\0\1\3\10\0\1\u016a"+
    "\2\3\1\u016b\5\3\1\u016c\45\3\2\0\2\3\17\0"+
    "\1\3\10\0\41\3\1\u016d\15\3\2\0\2\3\17\0"+
    "\1\3\10\0\33\3\1\u016e\23\3\2\0\2\3\17\0"+
    "\1\3\10\0\34\3\1\u016f\22\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\u0170\20\3\2\0\2\3\17\0"+
    "\1\3\10\0\17\3\1\u0171\37\3\2\0\2\3\17\0"+
    "\1\3\10\0\43\3\1\u0172\13\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\u0173\20\3\2\0\2\3\17\0"+
    "\1\3\10\0\40\3\1\u0174\16\3\2\0\2\3\17\0"+
    "\1\3\10\0\3\3\1\u0175\53\3\2\0\2\3\17\0"+
    "\1\3\10\0\37\3\1\u0176\17\3\2\0\2\3\17\0"+
    "\1\3\10\0\36\3\1\u0177\20\3\2\0\2\3\17\0"+
    "\1\3\10\0\37\3\1\u0178\17\3\2\0\2\3\17\0"+
    "\1\3\10\0\40\3\1\u0179\16\3\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[21075];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\7\1\6\11\1\1\3\11"+
    "\1\1\1\11\40\1\1\0\1\11\1\0\5\11\1\0"+
    "\2\11\1\0\1\11\1\1\3\11\60\1\3\0\1\11"+
    "\56\1\4\0\1\11\60\1\2\0\1\11\1\0\1\11"+
    "\50\1\2\0\40\1\1\0\27\1\1\11\60\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[377];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme,componenteL;
    public int linea, columna;
    public Symbol token(int simbolo){
            Lexema lexema = new Lexema( yytext() );
            return new Symbol(simbolo,yyline+1,yycolumn,lexema);
    }
    public Symbol token(int simbolo,String componenteLexico){
            Lexema lexema = new Lexema( yytext() );
            return new Symbol(simbolo,yyline+1,yycolumn,lexema);
    }
    public Symbol token(int simbolo,int linea, int columna,String lexeme,String componenteLexico){
            Lexema lexema = new Lexema( yytext() );
            componenteL=componenteLexico;
            //Principal.setError("La cadena "+yytext()+" es invalida, se encontro en la linea "+(yyline+1)+", y en la columna "+(yycolumn+1));
            return new Symbol(simbolo,yyline,yycolumn,lexema);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 90: 
          { return token(sym.getHour, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getHour");
          }
        case 112: break;
        case 31: 
          { return token(sym.OPERDECREMENTO, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"OPERDECREMENTO");
          }
        case 113: break;
        case 71: 
          { return token(sym.ARRAY, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ARRAY");
          }
        case 114: break;
        case 48: 
          { return token(sym.CSS, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"CSS");
          }
        case 115: break;
        case 29: 
          { return token(sym.MENORIGUAL, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"MENORIGUAL");
          }
        case 116: break;
        case 75: 
          { return token(sym.docOn, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"docOn");
          }
        case 117: break;
        case 103: 
          { return token(sym.makeTable, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"makeTable");
          }
        case 118: break;
        case 14: 
          { return token(sym.LLAVE_A, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"LLAVE_ABRIR");
          }
        case 119: break;
        case 99: 
          { return token(sym.FORMATTER, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"FORMATTER");
          }
        case 120: break;
        case 55: 
          { return token(sym.hvr, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"hvr");
          }
        case 121: break;
        case 33: 
          { return token(sym.ASIGNACIONMULT, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ASIGNACIONMULT");
          }
        case 122: break;
        case 30: 
          { return token(sym.DIFERENTE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"DIFERENTE");
          }
        case 123: break;
        case 27: 
          { System.out.println("Numero invalido"); return token(sym.INVNUMERO,linea=yyline+1,columna=yycolumn,lexeme=yytext(),"INVALID_NUMERO");
          }
        case 124: break;
        case 63: 
          { return token(sym.DATE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"DATE");
          }
        case 125: break;
        case 107: 
          { return token(sym.docGetElemID, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"docGetElemID");
          }
        case 126: break;
        case 76: 
          { return token(sym.CREATE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"CREATE");
          }
        case 127: break;
        case 79: 
          { return token(sym.RClass, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"RClass");
          }
        case 128: break;
        case 44: 
          { return token(sym.IF, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"IF");
          }
        case 129: break;
        case 57: 
          { return token(sym.THIS, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"THIS");
          }
        case 130: break;
        case 35: 
          { return token(sym.OR, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"OR");
          }
        case 131: break;
        case 3: 
          { System.out.println("Numero"); return token(sym.NUMERO,linea=yyline+1,columna=yycolumn,lexeme=yytext(),"NUMERO");
          }
        case 132: break;
        case 92: 
          { return token(sym.docCreateElemTag, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getDate");
          }
        case 133: break;
        case 61: 
          { return token(sym.LIST, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"LIST");
          }
        case 134: break;
        case 100: 
          { return token(sym.optSelect, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"optSelect");
          }
        case 135: break;
        case 20: 
          { return token(sym.COMA, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"COMA");
          }
        case 136: break;
        case 5: 
          { /*Ignore*/
          }
        case 137: break;
        case 101: 
          { return token(sym.getSecond, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getSecond");
          }
        case 138: break;
        case 70: 
          { return token(sym.Value, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"Value");
          }
        case 139: break;
        case 78: 
          { return token(sym.AClass, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"AClass");
          }
        case 140: break;
        case 50: 
          { return token(sym.VAR, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"VAR");
          }
        case 141: break;
        case 80: 
          { return token(sym.RChild, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"RChild");
          }
        case 142: break;
        case 17: 
          { return token(sym.CORCHETE_C, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"CORCHETE_CERRAR");
          }
        case 143: break;
        case 22: 
          { return token(sym.ANDSIMPLE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"AND_SIMPLE");
          }
        case 144: break;
        case 72: 
          { return token(sym.FALSE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"FALSE");
          }
        case 145: break;
        case 49: 
          { return token(sym.TRY, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"TRY");
          }
        case 146: break;
        case 9: 
          { return token(sym.MULTIPLICACION, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"MULTIPLICACION");
          }
        case 147: break;
        case 32: 
          { return token(sym.ASIGNACIONDECRE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ASIGNACIONDECRE");
          }
        case 148: break;
        case 41: 
          { return token(sym.HG, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"HG");
          }
        case 149: break;
        case 10: 
          { return token(sym.MAYORQUE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"MAYORQUE");
          }
        case 150: break;
        case 21: 
          { return token(sym.DOSPUNTOS, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"DOSPUNTOS");
          }
        case 151: break;
        case 68: 
          { return token(sym.Child, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"Child");
          }
        case 152: break;
        case 91: 
          { return token(sym.getYear, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getYear");
          }
        case 153: break;
        case 105: 
          { return token(sym.getMSecond, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getMSecond");
          }
        case 154: break;
        case 51: 
          { return token(sym.Val, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"Val");
          }
        case 155: break;
        case 81: 
          { return token(sym.RETURN, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"RETURN");
          }
        case 156: break;
        case 84: 
          { return token(sym.getAtt, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getAtt");
          }
        case 157: break;
        case 28: 
          { return token(sym.STRING,linea=yyline+1,columna=yycolumn,lexeme=yytext(),"STRING");
          }
        case 158: break;
        case 53: 
          { return token(sym.css, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"css");
          }
        case 159: break;
        case 23: 
          { return token(sym.XOR, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"XOR");
          }
        case 160: break;
        case 111: 
          { return token(sym.docCreateElemTag, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"docCreateElemTag");
          }
        case 161: break;
        case 64: 
          { return token(sym.ELSE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ELSE");
          }
        case 162: break;
        case 26: 
          { return token(sym.DIVISION, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"DIVISION");
          }
        case 163: break;
        case 97: 
          { return token(sym.fileName, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"fileName");
          }
        case 164: break;
        case 58: 
          { return token(sym.TRUE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"TRUE");
          }
        case 165: break;
        case 94: 
          { return token(sym.FUNCTION, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"FUNCTION");
          }
        case 166: break;
        case 60: 
          { return token(sym.MAPX, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"MAPX");
          }
        case 167: break;
        case 13: 
          { return token(sym.PARENTESIS_C, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"PARENTESIS_CERRAR");
          }
        case 168: break;
        case 83: 
          { return token(sym.JQElem, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"JQElem");
          }
        case 169: break;
        case 16: 
          { return token(sym.CORCHETE_A, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"CORCHETE_ABRIR");
          }
        case 170: break;
        case 89: 
          { return token(sym.setHTML, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"setHTML");
          }
        case 171: break;
        case 8: 
          { return token(sym.RESTA, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"RESTA");
          }
        case 172: break;
        case 108: 
          { return token(sym.docCreateElem, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"docCreateElem");
          }
        case 173: break;
        case 77: 
          { return token(sym.CONSOL, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"CONSOL");
          }
        case 174: break;
        case 34: 
          { return token(sym.MAYORIGUAL, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"MAYORIGUAL");
          }
        case 175: break;
        case 102: 
          { return token(sym.getMinute, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getMinute");
          }
        case 176: break;
        case 104: 
          { return token(sym.JQDocReady, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"JQDocReady");
          }
        case 177: break;
        case 88: 
          { return token(sym.outHTML, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"outHTML");
          }
        case 178: break;
        case 36: 
          { return token(sym.AND, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"AND");
          }
        case 179: break;
        case 12: 
          { return token(sym.PUNTO, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"PUNTO");
          }
        case 180: break;
        case 25: 
          { return token(sym.SUMA, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"SUMA");
          }
        case 181: break;
        case 56: 
          { return token(sym.HTML, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"HTML");
          }
        case 182: break;
        case 95: 
          { return token(sym.PrintCon, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"PrintCon");
          }
        case 183: break;
        case 66: 
          { return token(sym.COMENTARIO, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"COMMENT");
          }
        case 184: break;
        case 4: 
          { return token(sym.COMILLA_SIMPLE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"COMILLA_SIMPLE");
          }
        case 185: break;
        case 19: 
          { return token(sym.PUNTOCOMA, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"PUNTO_COMA");
          }
        case 186: break;
        case 65: 
          { return token(sym.PAGE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"PAGE");
          }
        case 187: break;
        case 69: 
          { return token(sym.TABLE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"TABLE");
          }
        case 188: break;
        case 87: 
          { return token(sym.DECLARE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"DECLARE");
          }
        case 189: break;
        case 82: 
          { return token(sym.Remove, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"Remove");
          }
        case 190: break;
        case 43: 
          { return token(sym.EN, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"EN");
          }
        case 191: break;
        case 62: 
          { return token(sym.NULL, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"NULL");
          }
        case 192: break;
        case 18: 
          { return token(sym.GUIONBAJO, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"GUION_BAJO");
          }
        case 193: break;
        case 38: 
          { return token(sym.ASIGNACIONINCRE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ASIGNACIONINCRE");
          }
        case 194: break;
        case 2: 
          { return token(sym.ID,linea=yyline+1,columna=yycolumn,lexeme=yytext(),"IDENTIFICADOR");
          }
        case 195: break;
        case 59: 
          { return token(sym.MAIN, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"MAIN");
          }
        case 196: break;
        case 85: 
          { return token(sym.inHTML, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"inHTML");
          }
        case 197: break;
        case 47: 
          { return token(sym.IGUAL2, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"IGUAL2");
          }
        case 198: break;
        case 106: 
          { return token(sym.beforeChild, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"beforeChild");
          }
        case 199: break;
        case 74: 
          { return token(sym.WHILE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"WHILE");
          }
        case 200: break;
        case 93: 
          { return token(sym.getBody, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getBody");
          }
        case 201: break;
        case 110: 
          { return token(sym.docGetElemClass, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"docGetElemClass");
          }
        case 202: break;
        case 42: 
          { return token(sym.TR, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"TR");
          }
        case 203: break;
        case 15: 
          { return token(sym.LLAVE_C, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"LLAVE_CERRAR");
          }
        case 204: break;
        case 98: 
          { return token(sym.ChildText, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ChildText");
          }
        case 205: break;
        case 40: 
          { return token(sym.ASIGNACIONDIV, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ASIGNACIONDIV");
          }
        case 206: break;
        case 11: 
          { return token(sym.PARENTESIS_A, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"PARENTESIS_ABRIR");
          }
        case 207: break;
        case 96: 
          { return token(sym.getMonth, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"getMonth");
          }
        case 208: break;
        case 6: 
          { return token(sym.MENORQUE, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"MENORQUE");
          }
        case 209: break;
        case 109: 
          { return token(sym.docGetElemTag, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"docGetElemTag");
          }
        case 210: break;
        case 45: 
          { return token(sym.JS, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"JS");
          }
        case 211: break;
        case 73: 
          { return token(sym.BREAK, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"BREAK");
          }
        case 212: break;
        case 39: 
          { return token(sym.OPERCREMENTO, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"OPERCREMENTO");
          }
        case 213: break;
        case 67: 
          { return token(sym.CATCH, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"CATCH");
          }
        case 214: break;
        case 24: 
          { return token(sym.ASIGNACION, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ASIGNACION");
          }
        case 215: break;
        case 37: 
          { return token(sym.IGUAL, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"IGUAL");
          }
        case 216: break;
        case 52: 
          { return token(sym.FOR, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"FOR");
          }
        case 217: break;
        case 46: 
          { return token(sym.WD, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"WD");
          }
        case 218: break;
        case 1: 
          { return token(sym.ERROR,linea=yyline+1,columna=yycolumn,lexeme=yytext(),"ERROR");
          }
        case 219: break;
        case 54: 
          { return token(sym.div, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"div");
          }
        case 220: break;
        case 7: 
          { return token(sym.NOT, linea=yyline+1,columna=yycolumn,lexeme=yytext(),"NOT");
          }
        case 221: break;
        case 86: 
          { 
          }
        case 222: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
